# This code is the property of John Dixon.
# Unless given my explicit permission, nobody may copy or redistribute this code.
html="C:/Users/WeeklySchedule.html"
description="C:/Users/Descriptions.txt"
finishedfile="C:/Users/"
